apiVersion: v1
kind: Service
metadata:
  name: simpleapi
  namespace: default
  labels:
    app: simpleapi
spec:
  type: NodePort
  selector:
    app: simpleapi
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31002
    protocol: TCP
